env:
  global:
    - REPO_DIR=py_slvs
    - BUILD_COMMIT=ed6635d59411abfb0eb650cdc192b865aaab410c
    - BUILD_DEPENDS="cython cmake scikit-build"
    - TEST_DEPENDS=pytest
    - PLAT=x86_64
    - UNICODE_WIDTH=32
    - REPO=https://upload.pypi.org/legacy/
    - TEST_REPO=https://test.pypi.org/legacy/
    - PYPI_USERNAME=realthunder
    - secure: "vLxi7ZRo9sMv0gpz0cYbOTloqxb9QaIGkiJZtS9DxuFw/Di5cGCCvuJ2j0r4Thu9IPanXzpdO2qSich2IwnEHxiOy0VTGWEE3tLnxgIwZN47GWpKnhBkF7RJUia94ROwVmDYz9ODOynG/h+RKUq4PH0nPLmWKDP39UubTbk0ghZw4uihjev1/bxuX/oEscN1XQMPU3iq87URkz83TGeTcS2TmIheKZ++B82CQcA6SmMKcs0Lr/dgxnRG5se0Z3c5MblECSvIB/fpPtr7lXmu6XcAP9jvThhFDb40x5ohNJay+t/fqdlswmJQut7zjxV7rtf98RSZILj4rYBLDCaKMetAx1zkGoZ8in1busdjyGYctgM6YrqkPWefA/IFn3qfbAdJZm6dDqf6Io9qd4/6N6yaAJovrxrrzZKAhxIcX7VhdhSMp3Jd8Ukcp9EQfPOIMdJFv7p51p3r9ZFBk3ZoV7sXf18vx1T2+53GBoFs3k2i4ViXbh9/QlnBc2YzuUpw0lm3zMxDRcE6KIjwu8W1I/03X/VGNoU7sWDukIadnSPl/VfNdgV9Gw5ADHwCkqRZHSy2/uiWXOL7C3LqmetAXrrBrgUPwUGhAv6dYXLhv3rzC+r68p4SQIm3NFUOzgmTkJEGrgU12SRnT2cBr4KEUvFnGpOvTAGIRiAmkfOypXY="

language: python
# Default Python version is usually 2.7
os: linux
python: 3.5
dist: trusty
services: docker
jobs:
  include:
  - os: osx
    language: generic
    osx_image: xcode12.5
    env:
      - MB_PYTHON_VERSION=3.7
      - MACOSX_DEPLOYMENT_TARGET=10.9
      - PLAT=universal2
  - os: osx
    language: generic
    osx_image: xcode12.5
    env:
      - MB_PYTHON_VERSION=3.8
      - MACOSX_DEPLOYMENT_TARGET=10.9
      - PLAT=universal2
  - os: osx
    language: generic
    osx_image: xcode12.5
    env:
      - MB_PYTHON_VERSION=3.9
      - MACOSX_DEPLOYMENT_TARGET=10.9
      - PLAT=universal2
  - os: osx
    language: generic
    osx_image: xcode12.5
    env:
      - MB_PYTHON_VERSION=3.10
      - MACOSX_DEPLOYMENT_TARGET=10.9
      - PLAT=universal2
  - os: osx
    language: generic
    osx_image: xcode12.5
    env:
      - MB_PYTHON_VERSION=3.11
      - MACOSX_DEPLOYMENT_TARGET=10.9
      - PLAT=universal2

  - os: linux
    env:
      - MB_PYTHON_VERSION=3.6
  - os: linux
    env:
      - MB_PYTHON_VERSION=3.7
  - os: linux
    env:
      - MB_PYTHON_VERSION=3.8
  - os: linux
    env:
      - MB_PYTHON_VERSION=3.9
  - os: linux
    env:
      - MB_PYTHON_VERSION=3.10
  - os: linux
    env:
      - MB_PYTHON_VERSION=3.11

before_install:
- source multibuild/common_utils.sh;
- source multibuild/travis_steps.sh;
- before_install;

install:
  # - clean_code $REPO_DIR $BUILD_COMMIT;
  - build_wheel $REPO_DIR $PLAT;

script:
- install_run $PLAT

after_success:
- >
  if [ -n "$TRAVIS_TAG" ]; then
    pip install twine;
    pip install pyOpenSSL ndg-httpsclient pyasn1 || true;
    python -m twine upload --skip-existing ${TRAVIS_BUILD_DIR}/wheelhouse/*.whl --repository-url $REPO -u $PYPI_USERNAME -p $PYPI_PASSWORD ;
    echo "Deployed to PyPI.";
  else
    echo "Not deploying as not a tagged commit.";
  fi
- >
  if [ "$TRAVIS_BRANCH" == "pypi_test" ]; then
    pip install twine;
    pip install pyOpenSSL ndg-httpsclient pyasn1 || true;
    ls ${TRAVIS_BUILD_DIR}/wheelhouse/;
    python -m twine upload --skip-existing ${TRAVIS_BUILD_DIR}/wheelhouse/*.whl --repository-url $TEST_REPO -u $PYPI_USERNAME -p $PYPI_PASSWORD ;
    echo "Deployed to test PyPI.";
  else
    echo "Not deploying as not a commit on test branch.";
  fi

cache:
- timeout: 300
- directories:
  - "$BUILD_CCACHE_DIR"
  - "$HOME/.ccache"
  - "$HOME/.cache/pcre"
  - "$HOME/.cache/swig"
